### PR TITLE
profile picture field improved

### PR DESCRIPTION
**Pull request by sana7044**
profile picture field improved

### CODE REVIEW

**Comment by marclupanc** [comment]
Do you think it would be possible to add a gap between header navigation tabs and users' avatar section? About 16px would work. 

Screenshot 2024-09-19 at 23 10 07

**Review by marclupanc — COMMENTED** [review]
Please check on suggestion

**Comment by sana7044** [comment]
> Please check on suggestion

Yes, I agree with this suggestion, and I have changed this portion.

**Review by marclupanc — APPROVED** [review]
👍

**Pull request merged**
