### PR TITLE
Artist Carousel

### LINKED ISSUE #129: Artist Carousel
> @stravid87:
> I love art and artist love showing off their art. I wonder if we can also find a way to use light boxes to highlight. This will provide another interesting angle that we can use. (It also is a great way to get people to the site. In fact, holding art competitions might even work better than essay competitions because it is so accessible).

### PR DESCRIPTION
**Pull request by arnonrdp**
Close #129

### CODE REVIEW

**Comment by stravid87** [comment]
On it: Thursday -- I'll review.

**Comment by arnonrdp** [comment]
I cannot agree more in terms of user friendly.
Let me do some improvements on it.

**Comment by arnonrdp** [comment]
@stravid87, I did some progress here:

- I removed all visual navigation (which circles at the bottom and arrows).
- I added the artist photo as the last one in the grid and it opens the artist slide.
- I also added an event for the left and right arrow keys when the detailed view is open.

I think it's important that the user can switch between photos when viewing them in detail. Because it would be very bad to have to close and open one by one.

@NJavokhir, would you like to review the code?

**Comment by NJavokhir** [comment]
I liked click image become full screen and arrows (next img, ...) for user friendly.

**Review by NJavokhir — COMMENTED** [review]
image


I think that, there is unnecessary space

**Comment by arnonrdp** [comment]
This blank space occurs because there is an unloaded image there.
@stravid87, can you try to upload an artist photo again? If there is any error, I need to solve it before we proceed.

**Review by NJavokhir — APPROVED** [review]
I approved all changes

**Comment by stravid87** [comment]
👍 I uploaded an artist photo this am with no error.

**Pull request merged**
