### PR TITLE
Feature/component testing

### PR DESCRIPTION
**Pull request by hermannleboss**
## SETUP UNIT & COMPONENT TESTING 
- Setup 
- Test ArticleSkeleton.vue 
- Test utils functions in date.js

---

Before requesting a review of this Pull Request, I certify that I have tested the following items in the application and all have passed my local tests without any side effects:

- [x] Logout and login;
- [x] Navigation between pages;
- [x] Creation of a new prompt;
- [x] Creation of a new entry;
- [x] Like and Dislike button;
- [x] Share button;
- [x] Exclusion of the newly created prompt;
- [x] Deletion of the newly created entry;

---

### CODE REVIEW

**Comment by arnonrdp** [comment]
@globe-and-citizen/team-1-test, I believe testing components should be merged into the `feature/testing` branch instead of the `develop` branch.

I think that would make more sense. Meanwhile, we are using the `feature/testing` branch to develop and learn more and more.

What are your thoughts on this?

**Comment by stravid87** [comment]
> @globe-and-citizen/team-1-test, I believe testing components should be merged into the `feature/testing` branch instead of the `develop` branch.
> 
> I think that would make more sense. Meanwhile, we are using the `feature/testing` branch to develop and learn more and more.
> 
> What are your thoughts on this?

I'm cool with my branch merging into Hermann's or Hermann's into mine. I agree, let's get all testing working before we merge to develop.

**Comment by stravid87** [comment]
@Hermann, I see you're using Istanbul. Let's just roll with that unless it starts to give trouble. It's mentioned in the official docs and so that's good enough for me.

**Comment by hermannleboss** [comment]
> @hermann, I see you're using Istanbul. Let's just roll with that unless it starts to give trouble. It's mentioned in the official docs and so that's good enough for me.

OK work for me, but this @hermann is not mee 🤣

**Comment by arnonrdp** [comment]
> > @hermann, I see you're using Istanbul. Let's just roll with that unless it starts to give trouble. It's mentioned in the official docs and so that's good enough for me.
> 
> OK work for me, but this @hermann is not mee 🤣

Man, that made me laugh a lot. 
Hahaha

**Comment by stravid87** [comment]
Please see latest pull request for branch <testing_for_merge>

**Pull request closed without merging**
