### PR TITLE
BugFix / Excessive Loading

### LINKED ISSUE #164: Fix excessive loading in Admin Page
Sometimes we see an excessive load on the Prompts and Entries management table.

This error is most likely related to `entries.js` store.

It has also been observed that sometimes refreshing the page does not prevent excessive loading.

I was able to prevent it by deleting the "entries" object from local storage.

### PR DESCRIPTION
**Pull request by arnonrdp**
Resolve #164

### CODE REVIEW

**Review by stravid87 — APPROVED** [review]
A few things: 

* I spent ~2 hours this am going through the code. I realize now that 1) I'm getting rusty on my VueJS skills; and 2) the application has gotten complicated enough that it takes me substantial time to follow the function calls to fully understand it. It is a complex piece of code -- well done! You'll notice that I didn't add specific suggestions -- I didn't have any. It's actually beyond edge of skill set for front end inline optimizations.
* Very clever pushing the need to load down onto sub components (e.g., line 24 of `src/pages/AdminPage.vue`.) By not holding up the onMounted() call for parent pages and components, there were significant improvements in load time and UX. This represents another step up in usability. 
* Though I didn't have anything to add inline, I did notice a pattern. On several pages, fetchPrompts(), fetchEntries(), or both are called. This means that navigating through the application, there is much reloading occurring invisibly in the background but still occurring.  On line 139 of prompts.js I added ```alert('fetch PROMPTS run')``` and on line 36 of entires.js I added ```alert('fetch ENTRIES run')```. I then navigated through the application watching the alerts pop up. I have, frankly, limited knowledge of SPAs but I'm quite certain that SPA's can persist data such that we can build a "cache layer" between front end <=> pinia <=> browser cache <=> firebase. I'm certain there is a way that we can cache prompts & entries locally. 
* Regarding testing: haha, you read my mind! Yes. Now that you've done these nice refactors which made noticeable improvements, I would say that's the next step pre-merge: testing. Of course.

**Comment by arnonrdp** [comment]
> * I spent ~2 hours this am going through the code. I realize now that 1) I'm getting rusty on my VueJS skills; and 2) the application has gotten complicated enough that it takes me substantial time to follow the function calls to fully understand it. It is a complex piece of code -- well done! You'll notice that I didn't add specific in line suggestions -- I didn't have any. It's actually beyond edge of my skill set for front end inline optimizations!

I responded you there.

> * Very clever pushing the need to load down onto sub components (e.g., line 24 of `src/pages/AdminPage.vue`.) By not holding up the onMounted() call for parent pages and components, there were significant improvements in load time and UX. This represents another step up in usability.

Yes, my intention is to make the code cleaner to facilitate maintenance.

> * Though I didn't have anything to add inline, I did notice a pattern. On several pages, fetchPrompts(), fetchEntries(), or both are called. This means that navigating through the application, there is much reloading occurring invisibly in the background but still occurring.  On line 139 of prompts.js I added `alert('fetch PROMPTS run')` and on line 36 of entires.js I added `alert('fetch ENTRIES run')`. I then navigated through the application watching the alerts pop up. I have, frankly, limited knowledge of PWAs but I'm quite certain that PWA's can persist data such that we can build a "cache layer" between front end <=> pinia <=> browser cache <=> firebase. I'm certain there is a way that we can cache prompts & entries locally.

I will study more of this. I believe IndexesDB will come in here.

> * Regarding testing: haha, you read my mind! Yes. Now that you've done these nice refactors which made noticeable improvements, I would say that's the next step pre-merge: testing. Of course.

I am on it.

**Comment by arnonrdp** [comment]
@stravid87, I'm merging so I can continue working on the prompt comments task.

That way we can all test the overload fix.

**Comment by stravid87** [comment]
> @stravid87, I'm merging so I can continue working on the prompt comments task.
> 
> That way we can all test the overload fix.

I'm not 


> @stravid87, I'm merging so I can continue working on the prompt comments task.
> 
> That way we can all test the overload fix.

What do you mean my "overload"?

**Comment by stravid87** [comment]
@arnonrdp 
I'm glad that you went a head and merged. We need to get you a JS buddy who's on your level to review with you. I seriously can't keep!

**Pull request merged**
