### PR TITLE
Changed UI layout for search page and user entries section

### PR DESCRIPTION
**Pull request by marclupanc**
Changed ui layout for the search page and user entries section, to make it also a desktop version and more responsive.
Screenshot 2024-03-23 at 17 30 12
Screenshot 2024-03-23 at 17 30 23

### CODE REVIEW

**Review by arnonrdp — CHANGES_REQUESTED** [review]
It is nice, good good.


https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/26576201/65f9c179-ac46-4902-9fbf-cc00d137c7ab

**Comment by arnonrdp** [comment]
@marclupanc, sorry, I didn't make it clear.
I thought I had recorded my video with audio but apparently, my microphone was off.

I thought the side-by-side prompts and entries looked really good, but there is a slight problem with the breakpoints: notice that in the screen recording I did, it starts with 3 columns, then reduces to 2, then increases to 3 again, and then reduces to two.

Can you avoid this "back and forth"?

**Comment by marclupanc** [comment]
https://drive.google.com/file/d/1qiNltOzGsQ5YcgH9TIaDUsW9sW3HcaeR/view?usp=sharing 
updated

**Review by arnonrdp — APPROVED** [review]
This is perfect!

**Pull request merged**
