### PR TITLE
Feature/cypress v2

### PR DESCRIPTION
**Pull request by hermannleboss**
## Setup Cypress E2E testing and CI/CD

I set up cypress and added some test use case 

1. Visite Home page and check if data is properly loaded
2. Visite Home page and navigate between pages

> We also have Component testing examples with cypress. It's interessing the way they are doing it. 
> I left it so we could play with it.

---

Before requesting a review of this Pull Request, I certify that I have tested the following items in the application and all have passed my local tests without any side effects:

- [x] Logout and login;
- [x] Navigation between pages;
- [x] Creation of a new prompt;
- [x] Creation of a new entry;
- [x] Like and Dislike button;
- [x] Share button;
- [x] Exclusion of the newly created prompt;
- [x] Deletion of the newly created entry;

---

### CODE REVIEW

**Comment by arnonrdp** [comment]
@hermannleboss, I'm reviewing this PR and some doubts and ideas have arisen, could you clarify?

1. I noticed that a lot of Quasar components were created for Cypress use. So that they are separated from the others and make reading easier, could you move them to a specific folder?
2. I believe that `cross-env` could be added to **devDependencies** so that it runs without everyone having to install them on their machines.
3. Wouldn't it be important to have documentation regarding the use of Cypress? It could stay in `CONTIBUTING.md` or it could even create a `TESTING.md` explaining the step-by-step usage.

Also, your branch looks great and I'm looking forward to seeing it merged into the `develop` branch.

**Comment by hermannleboss** [comment]
> @hermannleboss, I'm reviewing this PR and some doubts and ideas have arisen, could you clarify?
> 
> 1. I noticed that a lot of Quasar components were created for Cypress use. So that they are separated from the others and make reading easier, could you move them to a specific folder?
> 2. I believe that `cross-env` could be added to **devDependencies** so that it runs without everyone having to install them on their machines.
> 3. Wouldn't it be important to have documentation regarding the use of Cypress? It could stay in `CONTIBUTING.md` or it could even create a `TESTING.md` explaining the step-by-step usage.
> 
> Also, your branch looks great and I'm looking forward to seeing it merged into the `develop` branch.

1- For theses components are there just for demo.  
2- Cross env should be available by default no need to be installed
3- Yes we can make a documentation for how to use cypress

**Comment by stravid87** [comment]
@hermannleboss Great work getting this done: testing is the least sexy of the absolutely necessary tasks for software engineering! I'm going to be all over this learning this week and we'll aim to get this merged next week. Testing is an everyone problem so we'll all need to learn how to make this go and and how to add our own tests.

**Comment by arnonrdp** [comment]
> 1- For theses components are there just for demo. 
> 2- Cross env should be available by default no need to be installed 
> 3- Yes we can make a documentation for how to use cypress

1. Oh, I got it. I thought your PR was ready to be merged. Now I noticed you changed it to Draft;
2. Yeah, it seems you are right 👍 
3. Create just a few first steps and we can improve it together

**Review by arnonrdp — CHANGES_REQUESTED** [review]
I noticed when running `npm run cy:run` it creates and saves the videos:
Captura de Tela 2023-03-15 às 16 49 19

This is amazing!! But in my opinion it shouldn't be committed as that would significantly increase the size of the project, making it much heavier to be cloned or pulled.

Do you think we can add it to `.gitignore`? Or would it be better to leave it as it is and add a command to remove the videos?

**Comment by hermannleboss** [comment]
> I noticed when running `npm run cy:run` it creates and saves the videos:
> 
> Captura de Tela 2023-03-15 às 16 49 19
> 
> This is amazing!! But in my opinion it shouldn't be committed as that would significantly increase the size of the project, making it much heavier to be cloned or pulled.
> 
> Do you think we can add it to `.gitignore`? Or would it be better to leave it as it is and add a command to remove the videos?

Vidos folder are alezady ignored

**Review by arnonrdp — APPROVED** [review]

**Pull request merged**
