### PR TITLE
feat: add editor config rules and format code using prettier

### PR DESCRIPTION
**Pull request by hermannleboss**
Just apply existing editor config and pretier rules in my IDE and run `npm run format`

### CODE REVIEW

**Review by arnonrdp — APPROVED** [review]
We have two options here:
1. Go to `.editorconfig` and change `max_line_length` to `140`; or
1. Go to `.prettierrc` and change `"printWidth"` to `120`

On my screen, 140 works best, but let me know what works best for you because it is not good to have the line breaking in VSCode.

**Comment by hermannleboss** [comment]
I prefere update .prettierrc and change "printWidth" to 120

**Comment by hermannleboss** [comment]
At the end we decide to use 140. 
But if you want to change it, it's OK

**Comment by stravid87** [comment]
> At the end we decide to use 140.
Yeah I noticed. No I'm indifferent. Just so long as it works for everyone.

**Comment by hermannleboss** [comment]
Ok, I think a voting system will be useful. So we don't have to ask everyone if this is right for you.

**Pull request merged**
