### PR TITLE
Search case sensitive added

### PR DESCRIPTION
**Pull request by sana7044**
## Task
Fixed search issue: case-sensitive search now ignored.

## Description
I have implemented a fix by removing the backend search functionality since all the data is available client-side. To achieve this, I implemented computed properties computedUsers and filtered the data with the given query. I avoided using backend search as we already have all the data on the client side, so it's unnecessary to make requests to the backend. Additionally, while going through the documentation, I found that we can't search case-insensitive, so for that, we need to add an additional field like search_display_name, which I think is necessary.

### CODE REVIEW

**Review by arnonrdp — CHANGES_REQUESTED** [review]
We don't have all the data available in the client side.

Check the comparison between `develop` and `feat/manage-user-search-issue-353`
Captura de Tela 2024-03-24 às 16 57 56

Captura de Tela 2024-03-24 às 16 58 24

**Comment by sana7044** [comment]
@arnonrdp, all the users are being fetched, but why are they not displayed? We are showing the users where the user's `role` is not 'User'.

```javascript
async fetchUsers() {
  this._isLoading = true;
  onSnapshot(query(collection(db, 'users'), where('role', '!=', 'User')), (querySnapshot) => {
    const users = querySnapshot.docs.map((doc) => ({ uid: doc.id, ...doc.data() }));
    this.$patch({ _users: users });
    this._isLoading = false;
  });
}
```

However, during search, we are performing the following:

```javascript
async queryUsers(search) {
  this._isLoading = true;
  return await getDocs(
    query(collection(db, 'users'), where('displayName', '>=', search), where('displayName', '<=', search + '\uf8ff'))
  )
  .then((querySnapshot) => {
    const users = querySnapshot.docs.map((doc) => ({ uid: doc.id, ...doc.data() }));
    this.$patch({ _users: users });
  })
  .finally(() => (this._isLoading = false));
}
```

So, it's loading all users. Is this correct, or should we fetch the users and then filter out the users for the user list too in the client side?

**Comment by arnonrdp** [comment]
@sana7044, please do the following to perform the test correctly:
1. Go to the `develop` branch and search for the user "abcd". You will see a user returned;
2. Go to the `feat/manage-user-search-issue-353` branch and search for the user "abcd". You will not see any user being returned;

**Comment by sana7044** [comment]
@arnonrdp Yeah i agree the data will come i.e what i mention in the comment , because while fetching users, we are filtering the user check the query in the above comment.
While searching we are performing search in all the user.

**Comment by marclupanc** [comment]
Fixed the issues with case sensitive search. Filtering all the users that are already loaded from firebase. Filtering is made based on user name and email. 

Changed the look of the table. Added pagination for better user experience. Also added sticky top bar for the manage users table. 


https://github.com/user-attachments/assets/29e070b9-d431-4303-a0e9-3ad4ed1f8a48

**Review by arnonrdp — APPROVED** [review]
Finally worked!!
Nice job, guys!

**Pull request merged**
