### PR TITLE
Realtime Updates

### LINKED ISSUE #204: Get realtime updates for comments
Currently, when data is updated in the database (whether prompt, entry, comment or even a like), we need to fetch that data so that it is updated on our machines.

Explaining better: imagine that a user browsed the site and populated its storage with data at a prompt. Meanwhile, on the other side of the world, someone added a comment.

That user won't see the comment until they exit the prompt and come back to it again. Because the current functions are not constantly looking for new data in the Database.

The existing solution created by Firebase is the use of Realtime Updates.

> You can listen to a document with the onSnapshot() method. An initial call using the callback you provide creates a document snapshot immediately with the current contents of the single document. Then, each time the contents change, another call updates the document snapshot.

Source: https://firebase.google.com/docs/firestore/query-data/listen

### PR DESCRIPTION
**Pull request by arnonrdp**
Using `onSnapshot` to get realtime updates.

Applying first in the comments.

Closes #204

### CODE REVIEW

**Comment by stravid87** [comment]
Oh no! Not Vitest!
K, let me take a look tonight / tomorrow.

**Comment by hermannleboss** [comment]
> ## [Codecov](https://app.codecov.io/gh/globe-and-citizen/Celebrity-Fanalyzer/pull/205?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=globe-and-citizen) Report
> > Merging [#205](https://app.codecov.io/gh/globe-and-citizen/Celebrity-Fanalyzer/pull/205?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=globe-and-citizen) ([e274aaf](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/commit/e274aaf66d9fd4bf42e3871e649057255287381a)) into [develop](https://app.codecov.io/gh/globe-and-citizen/Celebrity-Fanalyzer/commit/494d2710bf0b5ab1a3c067030763034d2b68ae90?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=globe-and-citizen) ([494d271](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/commit/494d2710bf0b5ab1a3c067030763034d2b68ae90)) will **increase** coverage by `0.65%`.
> > The diff coverage is `72.41%`.
> 
> ```diff
> @@             Coverage Diff             @@
> ##           develop     #205      +/-   ##
> ===========================================
> + Coverage    69.01%   69.66%   +0.65%     
> ===========================================
>   Files           47       47              
>   Lines         1520     1500      -20     
>   Branches       283      281       -2     
> ===========================================
> - Hits          1049     1045       -4     
> + Misses         450      438      -12     
> + Partials        21       17       -4     
> ```
> 
> [Impacted Files](https://app.codecov.io/gh/globe-and-citizen/Celebrity-Fanalyzer/pull/205?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=globe-and-citizen)	Coverage Δ	
> [src/stores/comments.js](https://app.codecov.io/gh/globe-and-citizen/Celebrity-Fanalyzer/pull/205?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=globe-and-citizen#diff-c3JjL3N0b3Jlcy9jb21tZW50cy5qcw==)	`86.58% <71.42%> (+5.03%)`	⬆️
> [src/components/Posts/TheComments.vue](https://app.codecov.io/gh/globe-and-citizen/Celebrity-Fanalyzer/pull/205?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=globe-and-citizen#diff-c3JjL2NvbXBvbmVudHMvUG9zdHMvVGhlQ29tbWVudHMudnVl)	`89.58% <100.00%> (+0.07%)`	⬆️
> ... and [1 file with indirect coverage changes](https://app.codecov.io/gh/globe-and-citizen/Celebrity-Fanalyzer/pull/205/indirect-changes?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=globe-and-citizen)

DO you remark this report how the code coverage increase

**Comment by stravid87** [comment]
Seeing it change is very encouraging and reassuring. I was a student getting graded for the first 30 years of my life so it's very comforting and familiar to get a report card again!

**Comment by arnonrdp** [comment]
> DO you remark this report how the code coverage increase

This makes me feel so good!

<hr>

> Seeing it change is very encouraging and reassuring. I was a student getting graded for the first 30 years of my life so it's very comforting and familiar to get a report card again!

I liked the comparison.

<hr>

I'm completely stuck with Vitest on this branch. I can't fix the errors.
They started when I applied `onSnapshot`.
Even though everything works fine on localhost, Vitest keeps showing these errors.

**Comment by stravid87** [comment]
> 
The error is because the call work by adding a listener that THEN loads the data. That is, the "await" in Vitest only apply to the application of the listener, NOT the return of the listener. The only way I was able to solve this was a real hack: I added a manual timeout like: 

```
await new Promise((res, rej)=>{
  setTimemout(()=>{
    res()
  }, 1500)
})
```

This allows the snapshot a split second to run. Very hacky. But it worked. 

However, I'm in the process of revamping our Vitest suite -- so not matter we just ignored it here and you went ahead and merged.

**Pull request merged**
