### PR TITLE
Adding content re: the "Why" page.

### PR DESCRIPTION
**Pull request by stravid87**
## Description
Intention to Close #51. 
I  decided instead of creating a whole new page, to use a modal instead. Reading the original content, I felt it was too centered on my personal story and no longer reflected a team approach. This allowed much of the content to be removed. Also, I wanted to limit the number of pages added so that simplicity of user Navigation could be maintained.

Quasar made this easy because it provided out-of-the-box-functionality for a modal and also for an accordion drop down menu. Between these two additions to the website, I thought that the addition of another dedicated page was unnecessary. 

---
Before requesting a review of this Pull Request, I certify that I have tested the following items in the application and all have passed my local tests without any side effects:
- [x] Logout and login;
- [x] Navigation between pages;
- [x] Creation of a new prompt;
- [x] Creation of a new entry;
- [x] Like and Dislike button;
- [x] Share button;
- [x] Exclusion of the newly created prompt;
- [x] Deletion of the newly created entry;
---

### CODE REVIEW

**Comment by stravid87** [comment]
1) What is meant by "Exclusion of the newly created prompt"
2) I did not see how to delete a newly created _entry_, only a newly created _prompt_

**Comment by arnonrdp** [comment]
> 1. What is meant by "Exclusion of the newly created prompt"

You created a prompt for testing, this means to delete it.

> 2. I did not see how to delete a newly created _entry_, only a newly created _prompt_

Probably your develop branch is outdated. Just `git pull` it or `git merge develop` into your `stravid87:stravid87/why` branch.

**Comment by stravid87** [comment]
Probably ready to be reviewed. Let me finish my testing. 
I meant to reach out and ask if you could see / interact with draft pull requests -- question answered!
Let finish my testing and then make it a full pull request.

**Comment by stravid87** [comment]
Yup. You were totally correct. Pulling to update fixed the delete entry functionality but there are some other tests now that I need to rerun that I can't tell if errored from a break or otherwise -- will report back.

**Comment by stravid87** [comment]
Are the following state of development or errors I may have caused?
- Likes / Dislikes not working on the Entry only the Prompt
- After Prompt/Entry creation, the "Manage Prompts & Entries" needs to be manually refreshed.
- Anthrogram not enabled for Entries, only Prompts.
- When loading an Entry to edit, the "Prompt" field is not autopopulated.
- Share button works on Prompts but not Entries
- If a prompt is deleted before it's associated entries, the entries remain orphaned in Firestore.

**Comment by arnonrdp** [comment]
Most of these errors is a work in progress.

> If a prompt is deleted before it's associated entries, the entries remain orphaned in Firestore.

This one call my attention and I am going to work on it today.

**Review by arnonrdp — APPROVED** [review]

**Pull request merged**
