### PR TITLE
Feature/testing for merge bar graph

### PR DESCRIPTION
**Pull request by hermannleboss**
## Description

Add testing for Bargraph

---

Before requesting a review of this Pull Request, I certify that I have tested the following items in the application and all have passed my local tests without any side effects:

- [x] Logout and login;
- [x] Navigation between pages;
- [x] Creation of a new prompt;
- [x] Creation of a new entry;
- [x] Like and Dislike button;
- [x] Share button;
- [x] Exclusion of the newly created prompt;
- [x] Deletion of the newly created entry;

---

### CODE REVIEW

**Comment by stravid87** [comment]
Hm. there seems to be a breaking change. On both the Cloudflare preview and the my local build, the menu at the bottom no longer is rendering.
df3b34ac celebrity-fanalyzer pages dev_(iPhone SE)
localhost_9200_(iPhone SE)

**Comment by stravid87** [comment]
Yup test runs well: 
 ✓ src/stores/__tests__/auth.spec.js (1)
 ✓ src/utils/__test__/date.spec.js (4)
 ✓ src/components/__tests__/ArticleSkeleton.spec.js (1)
 ✓ src/components/__tests__/MainMenu.spec.js (1) 2842ms
 ✓ src/components/__tests__/Bargraph.vue.spec.js (1)   

Test Files  5 passed (5)
     Tests  8 passed (8)
      Time  53.13s (in thread 2.98s, 1782.44%)


 PASS  Waiting for file changes...
       press h to show help, press q to quit

**Review by stravid87 — CHANGES_REQUESTED** [review]
Somewhere there is a breaking change. I don't see it. Please let me know if you're not have the same trouble rendering locally.

**Comment by arnonrdp** [comment]
Here this branch doesn't even run.
I get the following error in the console:
```console
The package "esbuild-darwin-arm64" could not be found, and is needed by esbuild.

If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" flag. The "optionalDependencies" package.json feature is used
by esbuild to install the correct binary executable for your current platform.
```

But from what I've researched, this is not a problem with the branch itself, but with Apple's M1 chip.

I'm trying to fix this to look into the bottom menu issue.

**Comment by arnonrdp** [comment]
I fixed the M1 Mac issue by adding "esbuild-darwin-arm64" to "devDependencies".
I hate installing dependencies, but I haven't found another solution.

@stravid87 the Main Menu is working fine here.

@hermannleboss, I committed `.env.test` (I thought you have committed it yesterday). Ravi, you should be able to run tests without changing **VITE_RELEASE_STAGE**.

Guys, running tests on that branch works fine. I also disabled auth warnings and `setup-file.js` log. This will make the test console clearer and we can focus on the alerts that really matter:
Captura de Tela 2023-02-23 às 15 50 03

**Comment by hermannleboss** [comment]
@arnonrdp I have this issue on my side 

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for esbuild-darwin-arm64@0.15.18: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  arm64
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

My chipset can't support your new package.

**Comment by stravid87** [comment]
Running on the latest version of the branch, the rendering issue seems to be google chrome related? Maybe just me... 
image

**Comment by stravid87** [comment]
Okay: making the test pass was just a few simple tweaks to the testing file: 
```
describe('Main Menu Component', () => {
  beforeEach(async () => {
    setActivePinia(createPinia())
    const userStore = useUserStore()
    const userString = '{"sub": "WCeN1oLBMndoLKzNBCS7RccV9cz1?", "email": "algae.peach.153@example.com", "email_verified": true}'
    const credential = GoogleAuthProvider.credential(userString)
    const result = await signInWithCredential(auth, credential)
    const isNewUser = getAdditionalUserInfo(result)?.isNewUser
    const { email, displayName, photoURL, uid } = result.user
    console.log(result.user)
    if (isNewUser) {
      try {
        await setDoc(doc(db, 'users', uid), { email, displayName, photoURL })
      } catch (e) {
        console.log('MainMenu.spec.js error: ', e)
      }
    }
    await userStore.testing_loadUserProfile(result.user)
  })

  it('should display the admin panel if the user logged has the admin role', async () => {
    const userStore = useUserStore()
    const user = userStore.getUser

    expect(user.role).toBe('admin')
    let localUserString = localStorage.getItem('user')
    expect(localUserString.indexOf('role')).toBeTruthy()

    const mockRouter = {
      push: vitest.fn()
    }

    const wrapper = mount(MainMenu)
    expect(wrapper.html().indexOf('admin_panel_settings')).toBeGreaterThan(-1)
  })
```

**Comment by stravid87** [comment]
> @arnonrdp I have this issue on my side
> 
> ```
> npm ERR! code EBADPLATFORM
> npm ERR! notsup Unsupported platform for esbuild-darwin-arm64@0.15.18: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
> npm ERR! notsup Valid OS:    darwin
> npm ERR! notsup Valid Arch:  arm64
> npm ERR! notsup Actual OS:   win32
> npm ERR! notsup Actual Arch: x64
> ```
> 
> My chipset can't support your new package.

If I understand this issue correctly, to run our testing on Cloudflare, we need this pkg, "esbuild-darwin-arm64": "^0.15.18"
@hermannleboss can't run locally though if we include? I did not have a problem with this package locally.

**Comment by arnonrdp** [comment]
> @arnonrdp I have this issue on my side
> 
> ```
> npm ERR! code EBADPLATFORM
> npm ERR! notsup Unsupported platform for esbuild-darwin-arm64@0.15.18: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
> npm ERR! notsup Valid OS:    darwin
> npm ERR! notsup Valid Arch:  arm64
> npm ERR! notsup Actual OS:   win32
> npm ERR! notsup Actual Arch: x64
> ```
> 
> My chipset can't support your new package.

Sorry, you are right, I just removed it.

**Comment by stravid87** [comment]
Main menu didn't work in CHROME (and know right? since when dose Edge work and not Chrome?)
Simple fix thankfully.

**Review by arnonrdp — APPROVED** [review]
Nice job!

**Comment by stravid87** [comment]
Beautiful. One step closer!

**Pull request merged**
