### PR TITLE
Added notification when restricting an image

### LINKED ISSUE #173: [BUG] Changing Profile Picture
**Describe the bug**
When attempting to change the profile picture, if a large picture is uploaded, the change will show but then not save. Upon reload, it will be the same previous picture.  

**To Reproduce**
Change the profile picture to a large picture by file size. Save and reload. Firebase will not update and a subtle error will show in the console. 

**Screenshots**
https://user-images.githubusercontent.com/116566901/232222486-b795fe0f-769c-49e7-8b62-3b10012517b4.mp4

**Smartphone (please complete the following information):**
- Browser, chrome
- Mobile (OS unknown)

**Request / Fix
Warning or user feedback when a picture too large is uploaded preventing any updates to the UI until an appropriately sized picture is chosen.

### PR DESCRIPTION
**Pull request by arnonrdp**
Added `max-file-size` of 1MB to avoid errors.

Fix #173

### CODE REVIEW

**Comment by arnonrdp** [comment]
@stravid87, I asked Taiba to test it.
Once done, I will merge it.

**Comment by stravid87** [comment]
Beautiful: <max-file-size="1048487">
Terse. Simple. Effective.

**Comment by arnonrdp** [comment]
She asked me to try to improved it for more than 1MB.

I will check the possibility.

**Comment by NJavokhir** [comment]
If you allow me, I will review and merge this PR. It is interesting process. If I open PR, you will review and merge mine work. If you open PR, I will do that. That's just interesting and useful for me because I can learn you code and gain experience.

**Comment by arnonrdp** [comment]
> If you allow me, I will review and merge this PR. It is interesting process. If I open PR, you will review and merge mine. If you open PR, I will do that. That's just interesting and useful for me because I can learn your code and gain experience.

Absolutely, let's do that! Feel free to review and merge this one.

Just don't close the #173 because I intend to improve it even more.

**Pull request merged**
