### PR TITLE
feat:#580 Fixed ESLint issues

### LINKED ISSUE #580: Fix ESLint Issues and Setup Automatic Linting on Commit
**Description:**
We need to address current ESLint errors and warnings throughout the codebase and set up automatic linting to ensure code quality before any commit is made. This will help maintain consistent coding standards and prevent avoidable linting issues from being introduced in the future.

**Tasks:**
_Fix ESLint issues:_
- Review and resolve all existing ESLint errors and warnings in the codebase.
- Ensure no errors remain unless explicitly necessary (with justifications for specific rule disabling).

_Setup Pre-commit Hook for ESLint:_
- Use husky or another pre-commit hook tool to ensure that ESLint runs automatically before each commit.
- Ensure that the commit is blocked if any linting issues are detected.

_Verify Configuration:_
- Confirm that the ESLint configuration covers all relevant files (.Vue, JavaScript, TypeScript, etc.).
- Ensure that the ESLint rules align with the project's coding standards and conventions.

_Documentation:_
Update the project's README or CONTRIBUTING guide to document the new pre-commit linting process.

**Acceptance Criteria:**

All existing ESLint issues have been resolved.
ESLint runs automatically on each commit.
Commits are blocked if any linting issues exist.
The linting process is clearly documented in the project.

### PR DESCRIPTION
**Pull request by marclupanc**
### 🛠 Description
Fixes #580.

Run all linting script and fixed all issues. 
Implemented automating running of linter on commit for all the developers. 
Implemented checking of commit message that has to match: ``"<type>:#<ticketNumber> - <description>"`` and not be longer that 50 characters
Added new rules and instructions to ``CONTRIBUTING.md`` file.
Updated ``CODE_OF_CONDUCT.md``
Added ignore commit message when commiting an merge after resloving conflicts and leaving the default message.

### ✨ Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update ✅

### 🧠 Rationale behind the change

This changes allow us to mainain clean codebase and follow the same code standards and consistency.  

### 🧪 All Test Suites Passed?

- [x] Manual tested
- [x] Vitest
- [ ] Cypress

### 📸 Screenshots (optional)

Please provide some screenshot for relevant changes

### 🏎 Quick checklist

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by sana7044** [comment]
@marclupanc 
Would you change anything else? otherwise I will start testing.

**Comment by marclupanc** [comment]
> @marclupanc Would you change anything else? otherwise I will start testing.

This is done for a while, you can review it! @sana7044

**Review by sana7044 — CHANGES_REQUESTED** [review]
@marclupanc 
First, I merged the latest code from the develop branch because this PR had conflicts.
Then, I continued testing and during that time, this error appeared in the Admin panel.
Screenshot from 2024-10-03 11-50-33

**Comment by marclupanc** [comment]
> @marclupanc First, I merged the latest code from the develop branch because this PR had conflicts. Then, I continued testing and during that time, this error appeared in the Admin panel. Screenshot from 2024-10-03 11-50-33


Ok, so I fixed those issue, but please if you are taking the responsability to resolve conflicts on someones PR either do it till the end and fix all the issues that might appear (like this once which appeared because of duplicate code, which you could easily resolve), or just let the PR author know that they have an conflict that need attention.

**Review by sana7044 — APPROVED** [review]

**Pull request merged**
