### PR TITLE
Feature/change network to polygon mainet

### PR DESCRIPTION
**Pull request by achillegley**
update cmapaign contract address and owner address in .env
enhance insufficiant gas error message handling
add event event mit for promt and entry status auto change on payment proceed.

### CODE REVIEW

**Review by marclupanc — COMMENTED** [review]
Do we really need all this commented console.logs? :D Just to maintain clean code and best practises.

**Comment by arnonrdp** [comment]
> Do we really need all this commented console.logs? :D Just to maintain clean code and best practises.

@achillegley, I totally agree.

Could you please review it?

**Comment by achillegley** [comment]
sure will remove them.. thanks for feedbacks.

**Comment by arnonrdp** [comment]
Thanks for that @achillegley.

I also noticed you updated some environment variables.

Do you think I should update them in the production server as well?

**Comment by achillegley** [comment]
yes, just three(03) values changes. 
VITE_ADVERTISEMENT_CAMPAIGN_CONTRACT_ADDRESS  
VITE_ADVERTISEMENT_COMPAIGN_CONTRACT_OWNER
VITE_CURRENT_NETWORK_NAME
I"ve already updated them on cloudfare both production  and devs but you can double check.

**Comment by marclupanc** [comment]
Thank you for the update. 

One suggestion for the future and just fyi, on line 184 ( I will update this in my currently opened PR)

`const entries = computed(() => {
  return props.rows
})`

Let's try removing all unused functions in the as:
1. The computed property still takes up memory as it is created and stored in the component's reactive system.
2. Vue's reactivity system will still track changes to props.rows and potentially trigger updates to the computed property, even if you don’t use the computed property directly in your template or methods.
3. If props.rows is frequently updated, the computed property will recompute its value each time, which might be unnecessary and cause performance overhead.

**Pull request merged**
