### PR TITLE
Feature/cover post image

### LINKED ISSUE #2: Cover post image after scrolling
On the post page, I left the image cropped with `:ratio="21/9"`.

The mission here is to leave the entire image as soon as the screen loads.
When scrolling, the image should be reduced as in the example below:

### Before scrolling
Captura de Tela 2022-10-31 às 17 53 43

### After scrolling
Captura de Tela 2022-10-31 às 17 54 01

### PR DESCRIPTION
**Pull request by hermannleboss**
Cover post image reduce and annimation

Close #2

### CODE REVIEW

**Comment by stravid87** [comment]
Herman, do you have a Vercel page where I can see this in action? I love seeing the collaboration between you two!

**Review by arnonrdp — CHANGES_REQUESTED** [review]
I noticed that you had to install a dependency (`vueuse`) to make it work. And you did it 👏. But I think the mouse tracker can be done without an extra dependency. The official Vue documentation has something about this here: https://vuejs.org/guide/reusability/composables.html#mouse-tracker-example

There is a problem calling the `onScroll()` function. It's being called multiple times and that's not good for performance: imagine you have a page with a lot of comments, this function is being called while the user is scrolling.
---

I think the most important part is the zoom on the image you added. The goal here is to see the full image and then scroll and crop it (like a parallax).

I think it's possible to add this just by including this:
- https://quasar.dev/vue-components/parallax#introduction

---

#### Bonus:

Quasar have some solutions for scroll observers that are already included (no need to install extra dependencies):
- https://quasar.dev/vue-directives/intersection
- https://quasar.dev/vue-directives/scroll#introduction
- https://quasar.dev/vue-directives/scroll-fire

**Comment by arnonrdp** [comment]
> Herman, do you have a Vercel page where I can see this in action? I love seeing the collaboration between you two!

I will take care of this.

**Comment by hermannleboss** [comment]
> I noticed that you had to install a dependency (`vueuse`) to make it work. And you did it clap. But I think the mouse tracker can be done without an extra dependency. The official Vue documentation has something about this here: https://vuejs.org/guide/reusability/composables.html#mouse-tracker-example
> 
> There is a problem calling the `onScroll()` function. It's being called multiple times and that's not good for performance: imagine you have a page with a lot of comments, this function is being called while the user is scrolling.
> 
> I think the most important part is the zoom on the image you added. The goal here is to see the full image and then scroll and crop it (like a parallax).
> 
> I think it's possible to add this just by including this:
> 
> * https://quasar.dev/vue-components/parallax#introduction
> 
> ### Bonus:
> Quasar have some solutions for scroll observers that are already included (no need to install extra dependencies):
> 
> * https://quasar.dev/vue-directives/intersection
> * https://quasar.dev/vue-directives/scroll#introduction
> * https://quasar.dev/vue-directives/scroll-fire



OK i'm working on it.

**Comment by stravid87** [comment]
Nice effect. And thank you for the link. 
I'm going to try to do the same to learn Vercel.

**Comment by arnonrdp** [comment]
Hi @hermannleboss, are you still working on this issue?

**Comment by hermannleboss** [comment]
yes i'm still working on it, but i think i'm stuked

**Review by arnonrdp — COMMENTED** [review]
Try using a parallax, maybe.
The expected behavior is:

### On enter page:


### On scroll:


### After scrolling more:



No need to scale the image.

**Pull request merged**
