### PR TITLE
fix:#603 - Auto saving wallet when connected

### PR DESCRIPTION
**Pull request by marclupanc**
## Description

Removed the "Save" button, and automatically save the wallet address as soon as it is connected to the profile.

Updated the "+" button text based on the state of the user's wallet connection:
If the user has no wallet address linked to their profile, the hover text should read: "Connect your wallet."
If the user already has a wallet address connected to their profile, the hover text should read: "Update wallet address."

### CODE REVIEW

**Review by sana7044 — APPROVED** [review]

**Review by sana7044 — CHANGES_REQUESTED** [review]
When auto-saving the wallet during connection. I think the two wallet address fields are not needed.
Screenshot from 2024-09-25 16-35-30

**Comment by marclupanc** [comment]
> When auto-saving the wallet during connection. I think the two wallet address fields are not needed. Screenshot from 2024-09-30 11-29-56


@achillegley what do you think, do we need both fields in this implementation or we could keep just one? My thoughts was that we use one for current wallet and one for connected one, but it actually might not make sense anymore in this iimplementation.

**Comment by marclupanc** [comment]
> > When auto-saving the wallet during connection. I think the two wallet address fields are not needed. Screenshot from 2024-09-30 11-29-56
> 
> @achillegley what do you think, do we need both fields in this implementation or we could keep just one? My thoughts was that we use one for current wallet and one for connected one, but it actually might not make sense anymore in this iimplementation.

@achillegley ???

**Comment by achillegley** [comment]
Hi marc i can't see the image you attached. but i will check on the github page.

**Comment by marclupanc** [comment]
> Hi marc i can't see the image you attached. but i will check on the github page.

That's the first image Sana posted

**Comment by achillegley** [comment]
> > Hi marc i can't see the image you attached. but i will check on the github page.
> 
> That's the first image Sana posted

@marclupanc i missed your message. my point would be. 
If user don't have wallet address save it directly. is ok. 
if user already have wallet address and the new connected ( from metamask) is different  we should ask for confirmation with some message like  "would like to set this as your new wallet address ?".

**Comment by marclupanc** [comment]
Done, @sana7044 @achillegley please review

Screenshot 2024-10-08 at 20 50 53

**Comment by sana7044** [comment]
@marclupanc 
When the user tries to add a wallet address for the first time, an error popup appears, and the wallet address is not saved in firebase. After deleting the wallet address and trying again, it is added successfully and save in firebase. However, when attempting to change the wallet, some glitches are visible to the user.

https://www.awesomescreenshot.com/video/32361400?key=96a123cc55163504990a6ad5da0b8af1

**Comment by marclupanc** [comment]
> @marclupanc When the user tries to add a wallet address for the first time, an error popup appears, and the wallet address is not saved in firebase. After deleting the wallet address and trying again, it is added successfully and save in firebase. However, when attempting to change the wallet, some glitches are visible to the user.
> 
> https://www.awesomescreenshot.com/video/32361400?key=96a123cc55163504990a6ad5da0b8af1

@sana7044 
I am glad you found a bug, but I can't reproduce it, and I would need more details in order to fix it. You are showing only the pop-up error, is there any in console? Would be usefull... Maybe your network is different from Polygon Mainnet. For sure we need to handle all the errors but I can't reproduce yours, it all works for me.

https://vimeo.com/manage/videos/1017807786

**Comment by sana7044** [comment]
@marclupanc thanks.
I have tested this multiple times and conducted a deep analysis of the wallet address scenario, as this part is very important for our project.
**Steps to reproduce the issues**

1. First, create a new user with sign up.
2. Try to add a wallet address & delete. This works successfully.
3. Now, save a wallet address successfully.
4. Logout of this user and sign up with a new user.
5. You will see an error where the previous wallet address is still showing, even though the new user does not have a wallet address in Firebase.
6. Delete the displayed wallet address, but the edit icon is still shown instead of the expected add_circle icon.
7. When you click the edit icon, shows automatically adds a wallet address, even though no wallet address was selected.

https://www.awesomescreenshot.com/video/32370412?key=3e20ac3f30b4b0d3ab8d0089f24c1212

**Comment by marclupanc** [comment]
> @marclupanc thanks. I have tested this multiple times and conducted a deep analysis of the wallet address scenario, as this part is very important for our project. **Steps to reproduce the issues**
> 
> 1. First, create a new user with sign up.
> 2. Try to add a wallet address & delete. This works successfully.
> 3. Now, save a wallet address successfully.
> 4. Logout of this user and sign up with a new user.
> 5. You will see an error where the previous wallet address is still showing, even though the new user does not have a wallet address in Firebase.
> 6. Delete the displayed wallet address, but the edit icon is still shown instead of the expected add_circle icon.
> 7. When you click the edit icon, shows automatically adds a wallet address, even though no wallet address was selected.
> 
> https://www.awesomescreenshot.com/video/32370412?key=3e20ac3f30b4b0d3ab8d0089f24c1212

Added the empty walletAddress field for when the user registers so that when connecting the wallet it would just assign the address to the right field. Also added error logging to console for seeing more specific errors. Also resetting wallet store on logout which was causing persistent wallet address for new user.

**Pull request merged**
