### PR TITLE
Feat: Improves router navigation

### PR DESCRIPTION
**Pull request by sana7044**
Profile and Admin router updated, now user can directly access to the individual tab

### CODE REVIEW

**Review by arnonrdp — CHANGES_REQUESTED** [review]
Some changes are necessary:
- use `path` instead of `name` to navigate between routes;
- remove `name` keys from routes files;
- remove commented code

**Review by arnonrdp — APPROVED** [review]
Looks good to me.

**Review by arnonrdp — CHANGES_REQUESTED** [review]
Please fix `reports` route.

Captura de Tela 2024-03-24 às 17 29 40

**Comment by sana7044** [comment]
Fixed @arnonrdp 

> Please fix `reports` route.
> 
> Captura de Tela 2024-03-24 às 17 29 40

Fixed @arnonrdp

**Review by arnonrdp — APPROVED** [review]

**Pull request merged**
